version: "3"

services:

  neurio-export-mqtt:
    build:
      context: .
    restart: always
    environment:
      NEURIO_CLIENT_ID: "$NEURIO_CLIENT_ID"
      NEURIO_CLIENT_SECRET: "$NEURIO_CLIENT_SECRET"
      NEURIO_SENSOR_ID: "$NEURIO_SENSOR_ID"
      NEURIO_MQTT_SERVER: "$NEURIO_MQTT_SERVER"
      NEURIO_POLL_INTERVAL: 10
